// completionUsageCompletionTokensDetailsJSON contains the JSON metadata for the
// struct [CompletionUsageCompletionTokensDetails]
export class CompletionUsageCompletionTokensDetails {
	// When using Predicted Outputs, the number of tokens in the prediction that
	// appeared in the completion.
	accepted_prediction_tokens: number;

	// Audio input tokens generated by the model.
	audio_tokens: number;

	// Tokens generated by the model for reasoning.
	reasoning_tokens: number;

	// When using Predicted Outputs, the number of tokens in the prediction that did
	// not appear in the completion. However, like reasoning tokens, these tokens are
	// still counted in the total completion tokens for purposes of billing, output,
	// and context window limits.
	rejected_prediction_tokens: number;	

	static with(obj: any): CompletionUsageCompletionTokensDetails {
		if (!obj) return obj;
		Object.setPrototypeOf(obj, CompletionUsageCompletionTokensDetails.prototype);
		return obj;
	}
}

// Breakdown of tokens used in the prompt.
export class CompletionUsagePromptTokensDetails {
	// Audio input tokens present in the prompt.
	audio_tokens: number;
	// Cached tokens present in the prompt.
	cached_tokens: number;	

	static with(obj: any): CompletionUsagePromptTokensDetails {
		if (!obj) return obj;
		Object.setPrototypeOf(obj, CompletionUsagePromptTokensDetails.prototype);
		return obj;
	}
}

// Usage statistics for the completion request.
export class CompletionUsage {
	// Number of tokens in the generated completion.
	completion_tokens: number;

	// Number of tokens in the prompt.
	prompt_tokens: number;

	// Total number of tokens used in the request (prompt + completion).
	total_tokens: number;

	// Breakdown of tokens used in a completion.
	completion_tokens_details: CompletionUsageCompletionTokensDetails;

	// Breakdown of tokens used in the prompt.
	prompt_tokens_details: CompletionUsagePromptTokensDetails;
		

	static with(obj: any): CompletionUsage {
		if (!obj) return obj;
		Object.setPrototypeOf(obj, CompletionUsage.prototype);
		CompletionUsageCompletionTokensDetails.with(obj.completion_tokens_details);
		CompletionUsagePromptTokensDetails.with(obj.prompt_tokens_details);
		return obj;
	}

}

export class ModelUsageMetrics {
	Duration: number;
	EvaluatedPromptTokens: number;
	OpenAiUsage: CompletionUsage;	

	static with(obj: any): ModelUsageMetrics {
		if (!obj) return obj;
		Object.setPrototypeOf(obj, ModelUsageMetrics.prototype);
		CompletionUsage.with(obj.OpenAiUsage);
		return obj;
	}
}
