###
GET http://localhost:4080/rest/v1/commands

###
GET http://localhost:4080/rest/v1/commands/id/1

###
GET http://localhost:4080/rest/v1/repos/query?page=1&repoName=batch

###
GET http://localhost:4080/rest/v1/repos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjA4NjcyOCwiZXhwIjoxNzM1Njg2NzI4fQ.tJemJVz3XKeuD7x_3VpYMWRj008KA3iI4sPLG0yPYX4

###
DELETE http://localhost:4080/rest/v1/repos/id/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjA4NjcyOCwiZXhwIjoxNzM1Njg2NzI4fQ.tJemJVz3XKeuD7x_3VpYMWRj008KA3iI4sPLG0yPYX4


###
GET http://localhost:4080/rest/v1/repos/id/4

###
GET http://localhost:4080/rest/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjA4NjcyOCwiZXhwIjoxNzM1Njg2NzI4fQ.tJemJVz3XKeuD7x_3VpYMWRj008KA3iI4sPLG0yPYX4

###
GET http://localhost:4080/rest/v1/users/id/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjA4NjcyOCwiZXhwIjoxNzM1Njg2NzI4fQ.tJemJVz3XKeuD7x_3VpYMWRj008KA3iI4sPLG0yPYX4

###
DELETE http://localhost:4080/rest/v1/commands/id/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjA4NjcyOCwiZXhwIjoxNzM1Njg2NzI4fQ.tJemJVz3XKeuD7x_3VpYMWRj008KA3iI4sPLG0yPYX4

###
PATCH http://localhost:4080/rest/v1/commands/id/13/restart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjA4Njcy OCwiZXhwIjoxNzM1Njg2NzI4fQ.tJemJVz3XKeuD7x_3VpYMWRj008KA3iI4sPLG0yPYX4

###
POST http://localhost:4080/rest/v1/repos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjA4NjcyOCwiZXhwIjoxNzM1Njg2NzI4fQ.tJemJVz3XKeuD7x_3VpYMWRj008KA3iI4sPLG0yPYX4

{
  "path": "qiangyt/batchai"
}


###
GET http://localhost:4080/rest/v1/commands
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjA4NjcyOCwiZXhwIjoxNzM1Njg2NzI4fQ.tJemJVz3XKeuD7x_3VpYMWRj008KA3iI4sPLG0yPYX4

###
POST http://localhost:4080/rest/v1/commands
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTczMjA4NjcyOCwiZXhwIjoxNzM1Njg2NzI4fQ.tJemJVz3XKeuD7x_3VpYMWRj008KA3iI4sPLG0yPYX4

{
  "repoId": 6,
  "command": "check",
  "testLibraries": [
  ],
  "targetPaths": [
    "comm/file.go",
    "comm/io.go"
  ]
}

